const router = require('express').Router();
const c = require('./course.controller');
const { protect } = require('../../middleware/auth');
const { permit } = require('../../middleware/rbac');
const upload = require('../../config/storage');
router.use(protect);
router.get('/', c.getCourses);
router.post('/', permit('super_admin','branch_manager'), upload.single('coverImage'), c.createCourse);
router.get('/progress/me', c.getMyProgress);
router.post('/progress/complete', c.markComplete);
router.get('/lessons/:lessonId/materials', c.getMaterials);
router.post('/lessons/:lessonId/materials', permit('super_admin','branch_manager','teacher'), upload.single('file'), c.addMaterial);
router.delete('/materials/:materialId', permit('super_admin','branch_manager','teacher'), c.deleteMaterial);
router.get('/modules/:moduleId/lessons', c.getLessons);
router.post('/modules/:moduleId/lessons', permit('super_admin','branch_manager','teacher'), c.createLesson);
router.put('/lessons/:lessonId', permit('super_admin','branch_manager','teacher'), c.updateLesson);
router.delete('/lessons/:lessonId', permit('super_admin','branch_manager'), c.deleteLesson);
router.post('/lessons/:lessonId/unlock', permit('super_admin','branch_manager','teacher'), c.unlockLesson);
router.put('/modules/:moduleId', permit('super_admin','branch_manager','teacher'), c.updateModule);
router.delete('/modules/:moduleId', permit('super_admin','branch_manager'), c.deleteModule);
router.get('/:id', c.getCourse);
router.put('/:id', permit('super_admin','branch_manager','teacher'), upload.single('coverImage'), c.updateCourse);
router.delete('/:id', permit('super_admin','branch_manager'), c.deleteCourse);
router.post('/:id/enroll', permit('super_admin','branch_manager'), c.enrollStudents);
router.get('/:courseId/modules', c.getModules);
router.post('/:courseId/modules', permit('super_admin','branch_manager','teacher'), c.createModule);
module.exports = router;
